<!-- add ?lang=XX to current adress -->
<div class="languages">
    <a href="<?php echo $_SERVER['PHP_SELF'].'?lang=en';?>"><img class ="flags" src="./images/flags/flagEN.png" alt="EN" title="English"></a>
    <a href="<?php echo $_SERVER['PHP_SELF'].'?lang=fr';?>"><img class ="flags"  src="./images/flags/flagFR.png" alt="FR" title="Français"></a>
    <a href="<?php echo $_SERVER['PHP_SELF'].'?lang=de';?>"><img class ="flags" src="./images/flags/flagDE.png" alt="DE" title="Deutsch"></a>
    <a href="<?php echo $_SERVER['PHP_SELF'].'?lang=it';?>"><img class ="flags" src="./images/flags/flagIT.png" alt="IT" title="Italien"></a>
</div>